import previewView from './previewView.js'
import View from "./View.js";
import icons from '../../img/icons.svg';

/* The ResultsView class is a JavaScript class that extends the View class and is responsible for
rendering the results of a query in a specified parent element on a webpage. */
class ResultsView extends View {
  _parentElement = document.querySelector(".results");
  _errorMessage = 'No recipes found for your query! Try again!';
  _message = '';

   /**
    * The _generateMarkup function returns a string of HTML markup by mapping over the data array and
    * rendering each result using the previewView.
    * @returns a string that is generated by mapping over the `_data` array and rendering each element
    * using the `previewView.render()` function. The `false` argument passed to `previewView.render()`
    * indicates that the rendering should not include any additional details. The resulting rendered
    * elements are then joined together into a single string.
    */
   _generateMarkup() {
      return this._data
          .map(result => previewView.render(result, false))
          .join('');
  }
}

export default new ResultsView();



